### ISSUE TITLE
Curve point labels not appearing

### ISSUE THREAD

**Issue by jhillairet** [mtatsuma/MMM-WeatherChart#12]
First of all, thank you for module, it works great. 

Using the latest version of Magic Mirror on a raspberry pi, the curve point labels strangely do not appear as it should:

![image](https://user-images.githubusercontent.com/4642848/99185973-6c6d4e80-274d-11eb-8d42-5cd95cf3f590.png)

How can I help to debug if needed?

**Comment by mtatsuma** [comment]
Hi

Thank you for using the module!

I have confirmed that this module can work well for the latest version (v2.13.0) of MagicMirror and the data label for each point appears.

I guess the char.js [data label plugin](https://github.com/chartjs/chartjs-plugin-datalabels) is not loaded successfully on your environment.

You can check the console log from your browser and check if the plugin script is successfully loaded from https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0/dist/chartjs-plugin-datalabels.min.js.

**Comment by jhillairet** [comment]
OK. If I understand well, it seems so:
![image](https://user-images.githubusercontent.com/4642848/99292199-314c4780-2841-11eb-890c-157ad945d295.png)

I've removed the `node_modules` directory and restart, and now it works... thank you for pointing me toward the good direction.

**Comment by jhillairet** [comment]
ok, strangely it impacted another module, which now displays the labels while it didn't before... Do you know how to disable the label? :)
