### ISSUE TITLE
Hour format?

### ISSUE THREAD

**Issue by ger19wmu** [mtatsuma/MMM-WeatherChart#13]
First off, thanks for this module, I love the visual hourly info!

Would it be possible to get an option to change the display of time in the hourly format?  So rather than 24 hour format, a 12 hour format?  Instead of (11    12     13    14)  maybe something like (11a    12p    1p    2p)?

Thanks for the consideration!

**Comment by mtatsuma** [comment]
Thank you for using this module!

I'll try adding that config option. Please give me some time.

**Comment by mtatsuma** [comment]
I added a new config option `HourFormat`.

You can change to 12 hour format by cloning the latest version of module and adding `HourFormat: 12h` in config.js.
Please try it.

**Comment by ger19wmu** [comment]
Worked great!  And thanks for the fast turn around!!
