### ISSUE TITLE
Show Rain not converting to imperial 

### ISSUE THREAD

**Issue by ankonaskiff17** [mtatsuma/MMM-WeatherChart#15]
I have loaded MMM-WeatherChart in to my MM and set units to imperial. I'm in USA. Converts high and low temperatures as expected but not doing math to convert mm to inches.

**Comment by mtatsuma** [comment]
Hi

The `units` config param is simply passed to OpenWeather API. But OpenWeather API returns rain volume info with mm unit even when the units is specified as `imperial`.

Then, I added a new config param `rainUnit` with [the latest commit](https://github.com/mtatsuma/MMM-WeatherChart/commit/a730676198b2c27207d3fb4b58351b9769bacb1d) to change the unit of rain volume.

If you want to change it to inch, clone the latest module and add `"rainUnit": "inch"`  in your module config.

Please try it.

**Comment by ankonaskiff17** [comment]
That worked perfectly.

I tried to figure out how to contact you directly about that so put in problem report.

 

This was driven by person managing MagicMirror forum telling me not to edit the module file directly but to put all modifications in config.js file. I am not a programmer but I can sort of read and understand code.

 

I was looking at code and it seems like the minimum temperature are configured so that the minimum and maximum temperatures don’t overlap.  I can easily be wrong about that.

It seems like the rain volume scale (bottom line vertical axis) is too narrow so a small amount makes a significant trend. Is there a way to scale that to prevent it being such a big hump it seems like it is impacting the minimum and maximum temperatures causing them to overlap.

See attached jpg file.

**Comment by mtatsuma** [comment]
> See attached jpg file.

I cannot find the jpg file. Could you attach it directly to this issue page?

**Comment by ankonaskiff17** [comment]
No problem
![InkedWeatherChart_LI](https://user-images.githubusercontent.com/52932685/102012289-86cc2500-3d17-11eb-8c02-d703f6a4d2b7.jpg)

**Comment by mtatsuma** [comment]
Thank you for sharing the problem.

I added two changes to solve the problem.
https://github.com/mtatsuma/MMM-WeatherChart/pull/17
https://github.com/mtatsuma/MMM-WeatherChart/pull/18

To avoid the significant trend by the small amount rain, you can add a new param `rainMinHeight` and set it as a value that you think it is significant.
For example, if you think 0.1 inches of rain is significant, you should set `rainMinHeight` as 0.1.

Please clone the latest version of module and try it.

**Comment by ankonaskiff17** [comment]
That works great. Thank you.

I think I understand the minRainHeight but what I was wondering about would be more of maxRainHeight config option. minRainHeight would always = zero.

But maxRainHeight would be a config option.

That would be determined by individuals location. If you are auto scaling everything that won’t work but if you are only auto scaling the high and low temperatures it might. 

 

Tokyo maxRainHeight = X

Columbia, SC USA  maxRainHeight = Y   (<---My location)

Singapore maxRainHeight = Z

**Comment by mtatsuma** [comment]
> I think I understand the minRainHeight but what I was wondering about would be more of maxRainHeight config option. minRainHeight would always = zero.

I'm sorry for the confusion. rainMinHeight means minimum height of the rain volume (y-axis) in chart. So, it's the minimum rather than maximum. 
See this picture.
![image](https://user-images.githubusercontent.com/48573325/102484235-4c60e000-40a9-11eb-8806-42029326b877.png)

> That would be determined by individuals location. If you are auto scaling everything that won’t work but if you are only auto scaling the high and low temperatures it might.

It's almost impossible for me because there are many many places in the world and it's also difficult to get the place name from the latitude and longitude specified in config.
In my opinion, the adequate value of rainMinHeight depends on people rather than the location. So, it's enough to make it configurable.

**Comment by ankonaskiff17** [comment]
What I was trying to say was to let the maxRainHeight be configurable.

Here in South Carolina the maximum normal daily rain is probably less than 1 inches. So I would put in a value of 1 inches. 

 

A tropical rainforest country might see a daily maximum rainfall of 3 inches so that person would put in a value of 3 inches or equivalent mm number. I didn’t mean to imply plugging in values for every location.

 

Where you live has some daily rainfall average value. It is probably different than the value of where I live. That is all I was asking about.

 

But Thank you for what you have done it helps a bunch.

**Comment by mtatsuma** [comment]
> What I was trying to say was to let the maxRainHeight be configurable.

You mean you want to fix the y-axis scale to a configured value?
Actually, fixing the maximum height of rain volume to a value is not simple because there are temperature charts above the rain volume charts.

Anyway, this may be another requests that is not related to this issue.
If you have another problem or feature requests, please open a new issue with a appropriate title.
It's very helpful to clearly describe the problem with a screenshot!
