### ISSUE TITLE
Icons cover temperatur texts

### ISSUE THREAD

**Issue by keineAhnung667** [mtatsuma/MMM-WeatherChart#21]
Hello,
I just installed your module and like it.
But there is one thing that doesnt fit: the icons cover the temperature texts.

![Unbenannt](https://user-images.githubusercontent.com/71514327/103405263-d18ecf00-4b56-11eb-9a84-b2d36e3f19a0.png)

My config:

>            "module": "MMM-WeatherChart",
>             "position": "top_right",
>             "config": {
>                 "apiKey": "xyz",
>                 "lat": xyz,
>                 "lon": xyz,
>                 "units": "metric",
> 		"updateInterval": 15 * 60 * 1000,
> 		"title": "Wetter Münster",
> 		"showRain": true,
> 		"showIcon": true,
> 		"fillColor": "rgba(30, 144, 255, 0.2)",
>                 "dataNum": 13,
>                 "dataType": "hourly",
>                 "height": "400px",
>                 "width": "500px",
>             }

Btw: why changes the temperature line from 17 o'clock?

**Comment by mtatsuma** [comment]
Hi

Thank you for sharing the problem.
I added two patches to solve the problem.

1) The `width` and `height` module configs did not work well and I fixed that.
2)  Enable to change the icon size by setting `iconWidth` and ` iconHeight` module config.

So, to avoid the overlapping, please clone the latest module and you should adjust the configs `width`, `height`, `fontSize`, `iconWidth` and `iconHeight`.
For your above config, setting fontSize=14 or iconWidth/Height=40 may work well.

> Btw: why changes the temperature line from 17 o'clock?

The line style can be changed for night time temperature. See `nightBorderDash` config option in README.
