### ISSUE TITLE
If there is no rain -> hide rain chart

### ISSUE THREAD

**Issue by keineAhnung667** [mtatsuma/MMM-WeatherChart#24]
Hello mtatsuma,

I have a feature request:
Is it possible to hide the rain chart if there is no rain? Or at least hide the "0"s?

Example:
Right now:
![111](https://user-images.githubusercontent.com/71514327/104761587-67d01100-5763-11eb-80ae-1e7e0c213fae.png)
I think this would look better:
![222](https://user-images.githubusercontent.com/71514327/104761592-6868a780-5763-11eb-89c6-e1819d1bc392.png)

Thank you :)

**Comment by mtatsuma** [comment]
Hi

Thank you for the feature request!

I added an option to hide rain chart when there is no rain.
Please clone the latest module and set `"showZeroRain": false` in your module config.

**Comment by keineAhnung667** [comment]
Great, thats nice.
Maybe if showZeroRain is false and active, you could move the hours-axis more to top so there not so much empty space between the temperature line and the hour-axis ;)
