### ISSUE TITLE
Error on loading script

### ISSUE THREAD

**Issue by codac** [mtatsuma/MMM-WeatherChart#40]
I followed the instructions to git clone this module.
I'm using the following config.

{
            "module": "MMM-WeatherChart",
            "position": "top_right",
            "config": {
                "apiKey": "XXXXXXXXXXXXXXXXXXXXXXXX",
                "dataNum": 12,
                "dataType": "hourly",
                "height": "500px",
                "width": "800px",
                "lat": XX.XXXXXXX,
                "lon": X.XXXXXXX,
                "units": "metric",
                "showRain": true,
                "includeSnow": true,
                "showSnow": true,
                "showIcon": true
            }
        },

When reloading the mirror I do get the following errors:

Error on loading script: https://cdn.jsdelivr.net/npm/chart.js@3.4.0/dist/chart.min.js loader.js:194:10
Error on loading script: https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0/dist/chartjs-plugin-datalabels.min.js loader.js:194:10
Uncaught (in promise) ReferenceError: Chart is not defined MMM-WeatherChart.js:794:13

**Comment by mtatsuma** [comment]
Hi

Thank you for using this module.

The module loads the scripts successfully on my environment (v2.17.1 magicmirror and the latest MMM-WeatherChart module) and outputs following console logs.

```
Load script: modules/MMM-WeatherChart/MMM-WeatherChart.js
module.js:501 Check MagicMirror version for module 'MMM-WeatherChart' - Minimum version:  2.15.0 - Current version: 2.17.1
module.js:503 Version is ok!
module.js:509 Module registered: MMM-WeatherChart
loader.js:155 Bootstrapping module: MMM-WeatherChart
loader.js:184 Load script: https://cdn.jsdelivr.net/npm/chart.js@3.4.0/dist/chart.min.js
loader.js:184 Load script: https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0/dist/chartjs-plugin-datalabels.min.js
loader.js:160 Scripts loaded for: MMM-WeatherChart
loader.js:162 Styles loaded for: MMM-WeatherChart
```

Are you using some other modules on the same dashboard?
When the other module uses Chart.js with another version, the script loading may fail due to incompatibility between versions of Chart.js.

**Comment by codac** [comment]
My fault, NoScript Addon of my browser blocked it.
