### ISSUE TITLE
backgroundColor is not filling up the whole chart

### ISSUE THREAD

**Issue by MajorC1983** [mtatsuma/MMM-WeatherChart#44]
If I set backgroundColor, I only see a small line above the chart. Not as expected behind the whole chart.

**Comment by mtatsuma** [comment]
Hi

Could you tell me what value you set for backgroundColor?

**Comment by MajorC1983** [comment]
backgroundColor: "rgba(255, 0, 0, 1)"  so i see a 2px high solid red line

**Comment by MajorC1983** [comment]
it looks like that:
![Screenshot 2022-02-20 150113](https://user-images.githubusercontent.com/77094255/154846363-6df57b72-e355-4dca-8e6f-a25312c257a2.jpg)

**Comment by MajorC1983** [comment]
![Screenshot 2022-02-20 151212](https://user-images.githubusercontent.com/77094255/154846867-478348ad-0c15-472c-b324-4b79d3f47b24.jpg)

**Comment by mtatsuma** [comment]
Thank you.

Please give me some time to fix it.

**Comment by mtatsuma** [comment]
I fixed the issue.
Please clone the latest module and try it.

```
$ cd ~/MagicMirror/modules
$ git clone https://github.com/mtatsuma/MMM-WeatherChart.git
```

The result of my testing

<img width="929" alt="image" src="https://user-images.githubusercontent.com/48573325/155250773-cd848f76-2aa5-4b3e-bb51-4fdf18d69bdd.png">

**Comment by MajorC1983** [comment]
Works perfect. Thank you very much!
