### ISSUE TITLE
memory leak or something

### ISSUE THREAD

**Issue by luxiouronimo** [mtatsuma/MMM-WeatherChart#47]
i luv this module but after about a day my 1GB ram rpi3 will be out of memory and things will grind to a halt as (i assume) it struggles with swap/paged/virtual memory/or whatever..

i've just confirmed that without this module memory usage is more or less consistent (this setup has had a 250+ day uptime before updating to the latest MM), but since adding this module, as i've been monitoring it, the system becomes unusable after about a day.

**Comment by mtatsuma** [comment]
Thank you for telling me the issue.
I will investigate about that.

**Comment by mtatsuma** [comment]
@luxiouronimo I fixed the issue.
Please clone the latest version of MMM-WeatherChart module (v3.5.0) and try it.

Thank you!

**Comment by luxiouronimo** [comment]
that seems to have fixed it; at nearly 24hrs runtime i'm within 10mb memory usage of when i last `pm2 restart mm`'d; thank u thank u for the quick turnaround…

on a separate note, i use this with
```
	"dataNum": 48,
	"timeOffsetHours": -24,
	"dataType": "hourly",
```
as demonstrated in this screenshot:
![Screenshot 2022-12-25 at 8 08 23 AM](https://user-images.githubusercontent.com/1970784/209474938-2af84285-a000-4b99-b3d4-99b669df5ade.png)


feature request: can we get a (configurably colored) vertical line indicating the current time?

plz & thank u

**Comment by mtatsuma** [comment]
@luxiouronimo

>hiding the zeros in the precipitation (rain/snow/?) at the bottom would be nice…

You can set `"showZeroRain": false` and `"showZeroSnow": false` to hide the zeros.

For example:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/48573325/209546598-ad29c24f-88ad-4453-9153-6125ab5ab144.png">

>  if the time offset isn't a multiple of 24 then the nighttime dotted line is messed up..

I cannot reproduce the issue. It's helpful to show your full configuration and the captured display.

**Comment by luxiouronimo** [comment]
oo perfect, sorry i shoulda reviewed the readme and seen the showZero options…

does the timeOffsetHours work with negative numbers? so i can see the previous day as well as the next day?

**Comment by mtatsuma** [comment]
@luxiouronimo 
timeOffsetHours with negative number works, but you may be misunderstanding the config.

The displayed data is current and forecast weather (not the past weather). timeOffsetHours is used to shift and change the displayed hour numbers. The far left side of data always shows the current weather.
