### ISSUE TITLE
Step for the hourly forecast

### ISSUE THREAD

**Issue by dennisklad** [mtatsuma/MMM-WeatherChart#57]
Firstly thanks for the amazing module! 

Is there a way to set a step to display for example every second hour in the hourly forecast?
I have a small screen and can't show every hour, but would like to get the whole day on there.

Thanks!

**Comment by mtatsuma** [comment]
Hello @dennisklad 

Unfortunately, there are no way to set a step.
The hour label in x-axis is automatically omitted if you set `width` as a small value for your small screen as the folowing screenshot.

<img width="501" alt="image" src="https://github.com/user-attachments/assets/8f2b55f3-ac22-466e-a14b-313a768188c5">

I may be able to suggest a better configuration if you can share your config and screenshot.

**Comment by dennisklad** [comment]
Thanks for the reply.

This is my config:

```
{
      module: "MMM-WeatherChart",
      position: "top_right",
      config: {
              apiKey: "9b4e847341164e5f9917ce01ee453203",
              apiVersion: "3.0",
              apiEndpoint: "onecall",
              updateInterval: 10 * 60 * 1000,
              dataNum: 12,
              dataType: "hourly",
              height: "230px",
              width: "430px",
              lat: 52.490205844251676,
              lon: 13.324980946263821,
              units: "metric",
              showRain: true,
              showZeroRain: false,
              //includeSnow: true,
              showSnow: true,
              showZeroSnow: false,
              showIcon: true,
              datalabelsRoundDecimalPlace: 0,
      }
},
```

![image](https://github.com/user-attachments/assets/a8f53c21-2f42-4ab4-86e8-94878875f53c)

**Comment by mtatsuma** [comment]
I have tried the width and height in your config.

<img width="436" alt="image" src="https://github.com/user-attachments/assets/5c3ff4ce-0286-4973-852e-df9a49a3d699">

The figure on x-axis looks good. But the weater icons are overwrapped each other.

Your comment 
>I have a small screen and can't show every hour

means that the weather icons are not shown well?

**Comment by dennisklad** [comment]
Okay, that's fine. I though maybe there is a better way to do this :) 
Thanks!
