### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by c-m0s** [mtatsuma/MMM-WeatherChart#61]
Hi-
could you provide instructions for updating the WeatherChart module?

is it like:

### Update

1. git pull in the modules folder of MMM-WeatherChart
2. npm install in the same location
3. restart MagicMirror

Thanks, I love you module and do use it daily, @mtatsuma !

**Comment by mtatsuma** [comment]
Hello @c-m0s 

Yes, you can update it by
1. git pull the latest module
2. restart MagicMirror

Be careful that the latest MMM-WeatherChart updates the default OpenWeather API version and you may have to reproduce the API key.

**Comment by c-m0s** [comment]
thanks, I reinstalled my MagicMirror, but now I do have the same issues as #54 addresses.. :-(
