### ISSUE TITLE
Question about weather icons

### ISSUE THREAD

**Issue by 1Cedric1** [mtatsuma/MMM-WeatherChart#63]
Dear @mtatsuma,

great module you are providing!

you mention in readme that it is possible to use another set of weather icons.

let assume I have a set a icones I would like to uses, but how does it concrete work? 

Do you have a file to put them in?

Thanks in advance and have a great day!

Cédric

**Comment by mtatsuma** [comment]
Hello @1Cedric1 

When you place your icons on a website, you must configure iconURLBase as your site URL.

When you place all your icons at the path MMM-WeatherChart/images/, you must configure iconURLBase as modules/MMM-WeatherChart/images/.

Your image file names must be same with the openweather's ones documented [here](https://openweathermap.org/weather-conditions)

Give it a try and let me know if it doesn't work.

**Comment by 1Cedric1** [comment]
hello @mtatsuma 
and thank you for your reply.

I put some icons in a new folder in you module

![Capture d’écran 2024-12-09 à 18 21 35](https://github.com/user-attachments/assets/f43ddcb1-22e6-4a5a-adfd-89a5675556d9)

With "modules/MMM-WeatherChart/images/" as iconURLBase, 

![Capture d’écran 2024-12-09 à 18 22 08](https://github.com/user-attachments/assets/4b102e60-7e6d-4a85-a55e-a3212a453b19)

the current result is

![Capture d’écran 2024-12-09 à 18 26 31](https://github.com/user-attachments/assets/8798d8c4-5c1c-4822-9a98-682f7e1ea005)

instead of this one, with the basic configuration

![Capture d’écran 2024-12-09 à 18 26 56](https://github.com/user-attachments/assets/da4c8c29-2d98-4540-b666-2c3bf9775381)

I had changed the basic .svg extention in .png.

Do you think that could be the problem, or would it be with the URL?

Thank you in advance for your very appreciated help.

**Comment by mtatsuma** [comment]
@1Cedric1 
Is it possible to attach the PNG icon image for snow weather on this issue?
I will try the iconBaseURL config on my magicmirror environment.

I guess that 13n.png and 13d.png files are required for the snow icon.

**Comment by 1Cedric1** [comment]
hello @mtatsuma 
I do not know why, but it is suddenly working now  (!)
the only thing it that the icons are too large.
How did you manage to get smaller icons ?

**Comment by 1Cedric1** [comment]
hello @mtatsuma 
I do not know why, but it is suddenly working now  (!)
I had to find a convertor for .svg to .png, as the .svg icons are too large on the grafic.

anyway, thank you very much for your help, and congrats for your module !
