### ISSUE TITLE
Replace date with weekday?

### ISSUE THREAD

**Issue by theskyisthelimit** [mtatsuma/MMM-WeatherChart#9]
Hello,

Many thanks for this great module!

I just have a little question. Would it be possible to simply display the day of the week (Sa / So / Mo) instead of the date (i.e. 17 / 18 / 19)?

I think it would be a bit easier to read.

**Comment by mtatsuma** [comment]
Hi

Thank you for your request!
I created a patch to display days of the week label for daily forecast charts.

To display the label, you can add an option named `dailyLabel` in your module config and set it as `days_of_week`.
Please try it.

**Comment by theskyisthelimit** [comment]
Hi,

Sorry for the late reply.

I was able to test it and it works perfectly. Thank you so much!
